version: "3"

services:
  front:
    build:
      context: .
      dockerfile: react-Dockerfile
    container_name: react_wink
    restart: always
    image: react
    ports:
      - "3000:3000"
    volumes:
        - ./src/front:/app
        - /app/node_modules

